[package]
name = "juejin"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "*", features = ["rt", "rt-multi-thread", "macros"] }
reqwest = { version = "*", features = ["json"] }
serde_json = "*"
scraper = "*"
serde = { version = "1.0.215", features = ["derive"] }